volumes:
  sqlserver_data:
    name: sqlserver_data

services:
  sqlserver:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Developer
    user: root
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${DB_PASSWORD} -C -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
  sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    volumes:
      - sqlserver_data:/var/opt/mssql
    depends_on:
      sqlserver:
        condition: service_healthy
    command: >
      bash -c ' /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P ${DB_PASSWORD} -C -d master -i docker-entrypoint-initdb.d/init.sql; echo "All done!"; '
  backend:
    depends_on:
      - sqlserver
    image: ${DH_CREDENTIALS_USR}/amazon-clone-backend
    container_name: backend
    restart: always
    ports:
      - 5034:5034

  frontend:
    depends_on:
      - backend
    image: ${DH_CREDENTIALS_USR}/amazon-clone-frontend
    container_name: frontend
    restart: always
    ports:
      - 80:80
