---
apiVersion: apps/v1
kind: Deployment    
metadata:
  name: amazon-backend
  labels:
    app: amazon-backend
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: amazon-backend
  template:
    metadata:
      labels:
        app: amazon-backend
    spec:
      containers:
        - name: amazon-backend
          image: alkaponees/amazon-clone-backend:latest
          ports:
            - containerPort: 5034
---

apiVersion: v1
kind: Service    
metadata:
  name: amazon-backend
spec:
  selector:
    app: amazon-backend
  type: NodePort
  ports:
    - name: api
      protocol: TCP
      port: 5034
      targetPort: 5034
      nodePort: 5034
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: my-ingress
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: my-service
#                 port:
#                   number: 80